#!/usr/bin/env bash
set -euo pipefail

LIFE=".dna/genome"
PASS=0
FAIL=0

assert() {
  local name="$1" cmd="$2" expect="$3" output
  output=$(eval "$cmd" 2>&1) || true
  if echo "$output" | grep -q "$expect"; then
    echo "  ✓ $name"
    PASS=$((PASS + 1))
  else
    echo "  ✗ $name"
    echo "    expected: $expect"
    echo "    got: $(echo "$output" | head -3)"
    FAIL=$((FAIL + 1))
  fi
}

echo "=== Life 0.1 Test Suite ==="
echo

# --- Status ---
echo "life status:"
assert "finds repo" "$LIFE status" "Life repo:"
assert "counts directories" "$LIFE status" "Directories:"
assert "detects infra" "$LIFE status" "Infra:"

# --- Index ---
echo
echo "life index:"
assert "returns JSON" "$LIFE index" '"name"'
assert "includes blog" "$LIFE index" '"blog"'
assert "includes api" "$LIFE index" '"api"'
assert "includes root" "$LIFE index" '"hello-life"'
assert "blog provides blog.preview" "$LIFE index" 'blog.preview'
assert "api provides api.ready" "$LIFE index" 'api.ready'

# --- Explain ---
echo
echo "life explain:"
assert "explains blog" "$LIFE explain blog" "blog: Static site"
assert "shows requires" "$LIFE explain blog" "infra.compute"
assert "shows provides" "$LIFE explain blog" "blog.preview"
assert "shows commands" "$LIFE explain blog" "build"
assert "shows body" "$LIFE explain blog" "static site"
assert "explains api" "$LIFE explain api" "api: Backend"
assert "shows secrets" "$LIFE explain api" "DATABASE_URL"
assert "missing path" "$LIFE explain nonexistent" "No .life file"

# --- Check ---
echo
echo "life check:"
assert "blog checks pass" "$LIFE check blog" "blog check passed"
assert "api checks pass" "$LIFE check api" "api check passed"
assert "infra resolves via cloudflare" "$LIFE check blog" "infra.compute (cloudflare)"
assert "blog.preview resolves" "$LIFE check api" "blog.preview"
assert "missing secrets detected" "DATABASE_URL= API_KEY= $LIFE check api" "secret DATABASE_URL"
assert "set secrets pass" "DATABASE_URL=x API_KEY=y $LIFE check api" "secret DATABASE_URL"

# --- Graph ---
echo
echo "capability graph:"
assert "blog.preview flows blog→api" "$LIFE check api" "blog.preview (blog)"
assert "api.ready provided" "$LIFE index" "api.ready"
assert "infra.route resolves" "$LIFE check blog" "infra.route"

# --- Run ---
echo
echo "life run:"
assert "blog.build" "$LIFE run blog.build" "building blog"
assert "api.test" "$LIFE run api.test" "tests passed"
assert "api.health" "$LIFE run api.health" "healthy"
assert "migrate needs approval" "$LIFE run api.migrate" "requires approval"
assert "unknown fails" "$LIFE run nonexistent.build" "Not found"

# --- Connect ---
echo
echo "life connect:"
assert "no token fails" "CLOUDFLARE_API_TOKEN= CLOUDFLARE_ACCOUNT_ID= $LIFE connect cloudflare" "not set"
assert "unknown provider" "$LIFE connect nonexistent" "Unknown provider"

# --- Deploy ---
echo
echo "life deploy:"
assert "no token fails" "CLOUDFLARE_API_TOKEN= $LIFE deploy hello" "No infra"
assert "unknown dir fails" "$LIFE deploy nonexistent" "Not found"

# --- Reconcile ---
echo
echo "life reconcile:"
$LIFE reconcile > /dev/null 2>&1 || true
assert "generates CLAUDE.md" "cat CLAUDE.md" "Generated by Life"
assert "CLAUDE.md has blog" "cat CLAUDE.md" "blog"
assert "CLAUDE.md has api" "cat CLAUDE.md" "api"
rm -f CLAUDE.md AGENTS.md

# --- Live infra ---
if [ -n "${CLOUDFLARE_API_TOKEN:-}" ] && [ -n "${CLOUDFLARE_ACCOUNT_ID:-}" ]; then
  echo
  echo "live infra:"
  CONN=$($LIFE connect cloudflare 2>&1) || true
  if echo "$CONN" | grep -q "Connected"; then
    echo "  ✓ connect cloudflare"
    PASS=$((PASS + 1))

    DEP=$($LIFE deploy hello 2>&1) || true
    if echo "$DEP" | grep -q "deployed"; then
      echo "  ✓ deploy hello"
      PASS=$((PASS + 1))

      # Cleanup
      curl -s -X DELETE \
        "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/workers/scripts/hello" \
        -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" > /dev/null 2>&1
      echo "  (cleaned up)"
    else
      echo "  ✗ deploy hello: $(echo "$DEP" | head -1)"
      FAIL=$((FAIL + 1))
    fi
  else
    echo "  ✗ connect: $(echo "$CONN" | tail -1)"
    FAIL=$((FAIL + 1))
  fi
else
  echo
  echo "live infra: SKIPPED (no CLOUDFLARE_API_TOKEN)"
fi

# --- Summary ---
echo
echo "==========================="
echo "$PASS passed, $FAIL failed"
echo "==========================="
[ "$FAIL" -eq 0 ] || exit 1
